#!/bin/bash

#VARIABLES
# DATA=/data/orientdb
# CONFIG=/etc/orientdb/config

#STOP OLD CONTAINER
docker stop neo4j
docker rm neo4j

#RUN CONTAINER
docker build --quiet=false -t sscheffler/neo4j -rm=true .
