FROM sscheffler/jdk

MAINTAINER Stefan Scheffler (stefan-scheffler@web.de)

WORKDIR /data

# ENVIRONMENT VARIABLES
ENV JAVA_HOME=/opt/jdk7

# CMD ["/opt/logstash/bin/logstash","agent","-f","/data/config/config.conf"]
